version: '3'
services:
  app:
    image: {{ docker_image }}
    ports:
      - "{{ ports }}"
    deploy:
      resources:
        limits:
          cpus: "{{ cpus }}"
          memory: "{{ memory }}"
    volumes:
      - "{{ volume_mount }}"
