- hosts: all
  become: yes
  tasks:
    - name: Install-Docker-Docker Compose
      include_role:
        name: docker_setup
      
    - name: DeployDocker
      template:
        src: docker-compose.yml
        dest: /path/to/remote/docker-compose.yml

